env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - RELEASE_BUILDS=dist/kubekutr_darwin_amd64/kubekutr dist/kubekutr_linux_amd64/kubekutr dist/kubekutr_windows_amd64/kubekutr.exe

builds:
  - binary: kubekutr
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE

snapcrafts:
  - name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    summary: Cookie cutter templating tool for scaffolding K8s manifests.
    description: |
      kubekutr lets you quickly scaffold a bespoke configuration for Kubernetes resource manifests with an opinionated GitOps
      directory structure.
    grade: stable
    confinement: strict
    publish: true
